'use client';
import {useEffect,useRef,useState} from 'react';
import {LANGUAGES,LOCALES,NATIVE_NAMES,messages,tr,isLanguage,type Language,type MessageKey} from '@/lib/i18n';
import {fallbackResult,parseText} from '@/lib/explanations';
import {prepareFile} from '@/lib/files';
import type {AnalyzeResult,ExplainedRow,ExtractedRow,Flag} from '@/lib/types';

type View='home'|'upload'|'dashboard'|'history'|'questions'|'settings';
type Saved=AnalyzeResult&{id:string;name:string;date:string;language:Language;source:'file'|'manual'|'camera'};
type Location={view:View;reportId?:string};
type Upload={file:File;url:string;source:'file'|'camera'};
const flags:Flag[]=['normal','high','low','not_assessed'];
const symbols:Record<Flag,string>={normal:'✓',high:'↑',low:'↓',not_assessed:'?'};
function Icon({name}:{name:string}){const paths:Record<string,string>={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',upload:'M12 16V3m-5 5 5-5 5 5 M4 16v5h16v-5',history:'M3 11a9 9 0 1 1 2 7 M3 4v7h7 M12 7v5l3 2',chat:'M4 4h16v13H9l-5 4z',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',file:'M6 2h8l4 4v16H6z M14 2v5h4M9 12h6m-6 4h6',shield:'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6z M8 12l3 3 5-6',audio:'M11 4 5 9H2v6h3l6 5z M15 8a6 6 0 0 1 0 8 M18 4a11 11 0 0 1 0 16',arrow:'M4 12h16m-6-6 6 6-6 6',camera:'M3 6h4l2-3h6l2 3h4v15H3z M12 9a4 4 0 1 0 0 8 4 4 0 0 0 0-8'};return <svg viewBox="0 0 24 24" width="21" height="21" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.file}/></svg>}
function isSaved(value:unknown):value is Saved{const r=value as Saved;return !!r&&typeof r.id==='string'&&typeof r.name==='string'&&typeof r.date==='string'&&Number.isFinite(Date.parse(r.date))&&Array.isArray(r.rows)&&r.rows.length<=100&&r.rows.every(x=>x&&typeof x.nameAsPrinted==='string'&&(x.value===null||typeof x.value==='number'&&Number.isFinite(x.value))&&(x.unit===null||typeof x.unit==='string')&&(x.printedRange===null||typeof x.printedRange==='string'));}
function errorKey(error:unknown):MessageKey{const code=error instanceof Error?error.message:'';return Object.prototype.hasOwnProperty.call(messages,code)?code as MessageKey:error instanceof Error&&/Abort|Timeout/.test(error.name)?'TIMEOUT':'NETWORK';}
export default function App(){
 const [view,setView]=useState<View>('home');const [history,setHistory]=useState<Saved[]>([]);const [activeId,setActiveId]=useState<string|null>(null);
 const [language,setLanguage]=useState<Language>('English');const languageRef=useRef<Language>('English');const t=(key:MessageKey)=>tr(language,key);
 const [large,setLarge]=useState(false);const [contrast,setContrast]=useState(false);const [saveLocal,setSaveLocal]=useState(false);const [ready,setReady]=useState(false);
 const [upload,setUpload]=useState<Upload|null>(null);const [preparing,setPreparing]=useState(false);const fileGeneration=useRef(0);
 const [rows,setRows]=useState<ExtractedRow[]|null>(null);const [manual,setManual]=useState('');const [unreadableCount,setUnreadableCount]=useState(0);const [consent,setConsent]=useState(false);
 const [error,setError]=useState<MessageKey|null>(null);const [notice,setNotice]=useState<MessageKey|null>(null);const [ai,setAi]=useState<boolean|null>(null);
 const [stage,setStage]=useState<'reading'|'explaining'|null>(null);const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [sort,setSort]=useState('new');
 const [detailIndex,setDetailIndex]=useState<number|null>(null);const dialog=useRef<HTMLDialogElement>(null);const [speaking,setSpeaking]=useState(false);
 const chooser=useRef<HTMLInputElement>(null);const cameraPicker=useRef<HTMLInputElement>(null);const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const [cameraOpen,setCameraOpen]=useState(false);const [cameraStarting,setCameraStarting]=useState(false);const [cameraReady,setCameraReady]=useState(false);const cameraGeneration=useRef(0);
 const controller=useRef<AbortController|null>(null);const translationController=useRef<AbortController|null>(null);const job=useRef(0);
 const locations=useRef<Location[]>([{view:'home'}]);const cursor=useRef(0);const [navState,setNavState]=useState({cursor:0,length:1});
 const selected=history.find(r=>r.id===activeId)||null;
 const report=selected?(selected.language===language?selected:{...selected,...fallbackResult(selected.rows,language),language}):null;
 const reportName=(r:Saved)=>r.source==='manual'?t('manualReport'):r.source==='camera'?t('scannedReport'):r.name;
 const locale=LOCALES[LANGUAGES.indexOf(language)];
 function stopVoice(){if(typeof window!=='undefined')window.speechSynthesis?.cancel();setSpeaking(false);}
 function closeCamera(){cameraGeneration.current++;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;setCameraOpen(false);setCameraReady(false);setCameraStarting(false);}
 function resetTransient(){closeCamera();stopVoice();setError(null);setDetailIndex(null);setSearch('');setFilter('all');window.scrollTo(0,0);}
 function go(next:View,reportId?:string){if(stage)return;resetTransient();const target={view:next,reportId:reportId||activeId||undefined};if(locations.current[cursor.current].view!==next||locations.current[cursor.current].reportId!==target.reportId){locations.current=locations.current.slice(0,cursor.current+1);locations.current.push(target);cursor.current++;}setView(next);if(reportId)setActiveId(reportId);setNavState({cursor:cursor.current,length:locations.current.length});}
 function move(delta:number){if(stage)return;const next=cursor.current+delta;if(next<0||next>=locations.current.length)return;cursor.current=next;const target=locations.current[next];resetTransient();setView(target.view);if(target.reportId)setActiveId(target.reportId);setNavState({cursor:next,length:locations.current.length});}
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('mediexplain-settings')||'{}');if(isLanguage(s.language)){setLanguage(s.language);languageRef.current=s.language;}setLarge(!!s.large);setContrast(!!s.contrast);setSaveLocal(!!s.saveLocal);const h=JSON.parse(localStorage.getItem('mediexplain-history')||'[]');if(Array.isArray(h))setHistory(h.filter(r=>r?.demo!==true&&isSaved(r)).slice(0,30).map(r=>({...r,source:r.source||'file',...fallbackResult(r.rows,isLanguage(r.language)?r.language:'English'),language:isLanguage(r.language)?r.language:'English'})));}catch{setNotice('STORAGE');}setReady(true);fetch('/api/analyze',{cache:'no-store'}).then(r=>r.json()).then(r=>setAi(!!r.aiAvailable)).catch(()=>setAi(null));return()=>{controller.current?.abort();translationController.current?.abort();stream.current?.getTracks().forEach(track=>track.stop());window.speechSynthesis?.cancel();};},[]);
 useEffect(()=>{document.documentElement.lang=locale;document.title=`MEDIEXPLAIN · ${t('companion')}`;},[language]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('mediexplain-settings',JSON.stringify({language,large,contrast,saveLocal}));if(saveLocal)localStorage.setItem('mediexplain-history',JSON.stringify(history));else localStorage.removeItem('mediexplain-history');}catch{setNotice('STORAGE');}},[ready,language,large,contrast,saveLocal,history]);
 useEffect(()=>()=>{if(upload?.url)URL.revokeObjectURL(upload.url);},[upload]);
 useEffect(()=>{if(detailIndex!==null)dialog.current?.showModal();else dialog.current?.close();},[detailIndex]);
 useEffect(()=>{if(cameraOpen&&video.current&&stream.current){video.current.srcObject=stream.current;video.current.play().catch(()=>{setError('CAMERA_UNAVAILABLE');closeCamera();});}},[cameraOpen]);
 async function choose(file?:File,source:'file'|'camera'='file'){if(!file)return;const generation=++fileGeneration.current;setPreparing(true);setError(null);setRows(null);setUnreadableCount(0);try{const prepared=await prepareFile(file);if(generation!==fileGeneration.current)return;const url=URL.createObjectURL(prepared);setUpload({file:prepared,url,source});setConsent(false);}catch(e){if(generation===fileGeneration.current){setUpload(null);setError(errorKey(e));}}finally{if(generation===fileGeneration.current)setPreparing(false);}}
 function removeUpload(){fileGeneration.current++;setUpload(null);setRows(null);setPreparing(false);setConsent(false);}
 async function openCamera(){setError(null);if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){setNotice('CAMERA_SECURE');cameraPicker.current?.click();return;}const generation=++cameraGeneration.current;setCameraStarting(true);try{const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:2560},height:{ideal:1920}},audio:false});if(generation!==cameraGeneration.current){media.getTracks().forEach(track=>track.stop());return;}stream.current=media;setCameraOpen(true);}catch(e){setError(e instanceof Error&&e.name==='NotAllowedError'?'CAMERA_DENIED':'CAMERA_UNAVAILABLE');}finally{if(generation===cameraGeneration.current)setCameraStarting(false);}}
 async function capture(){if(!video.current||!cameraReady)return;const v=video.current;const canvas=document.createElement('canvas');canvas.width=v.videoWidth;canvas.height=v.videoHeight;const ctx=canvas.getContext('2d');if(!ctx||!canvas.width||!canvas.height){setError('CAMERA_UNAVAILABLE');return;}ctx.drawImage(v,0,0);const generation=cameraGeneration.current;const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.95));if(generation!==cameraGeneration.current)return;if(!blob){setError('DECODE');return;}closeCamera();await choose(new File([blob],'camera-report.jpg',{type:'image/jpeg'}),'camera');}
 async function send(payload:object,lang:Language,signal:AbortSignal){let response;try{response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,language:lang}),signal});}catch(e){if(e instanceof Error&&e.name==='AbortError')throw e;throw Error('NETWORK');}let data;try{data=await response.json();}catch{throw Error('BAD_RESPONSE');}if(!response.ok)throw Error(typeof data.code==='string'?data.code:'SERVICE');return data;}
 async function readReport(){if(!upload||!consent)return;setError(null);setStage('reading');const current=++job.current;const abort=new AbortController();controller.current=abort;const timer=setTimeout(()=>abort.abort(),55000);try{const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('DECODE'));reader.readAsDataURL(upload.file);});if(current!==job.current)return;const data=await send({imageBase64:base64,mimeType:upload.file.type},languageRef.current,abort.signal);if(current!==job.current)return;if(!Array.isArray(data.extracted)||!data.extracted.length)throw Error('UNREADABLE');setRows(data.extracted);setUnreadableCount(data.unreadableCount||0);}catch(e){if(current===job.current)setError(errorKey(e));}finally{clearTimeout(timer);if(current===job.current)setStage(null);}}
 async function confirm(){if(!rows?.length||rows.some(r=>!r.nameAsPrinted.trim())){setError('VALUES');return;}setError(null);setStage('explaining');const current=++job.current;const abort=new AbortController();controller.current=abort;const timer=setTimeout(()=>abort.abort(),55000);try{const lang=languageRef.current;const data=await send({rows},lang,abort.signal);if(current!==job.current)return;if(!Array.isArray(data.rows))throw Error('BAD_RESPONSE');const saved:Saved={...data,id:crypto.randomUUID(),name:upload?.file.name||'',date:new Date().toISOString(),language:lang,source:upload?.source||'manual'};setHistory(h=>[saved,...h].slice(0,30));setActiveId(saved.id);setRows(null);setStage(null);resetTransient();setView('dashboard');locations.current=locations.current.slice(0,cursor.current+1);locations.current.push({view:'dashboard',reportId:saved.id});cursor.current++;setNavState({cursor:cursor.current,length:locations.current.length});if(data.noticeCode)setNotice('translationFallback');}catch(e){if(current===job.current)setError(errorKey(e));}finally{clearTimeout(timer);if(current===job.current)setStage(null);}}
 function cancel(){job.current++;controller.current?.abort();setStage(null);}
 async function changeLanguage(next:Language){languageRef.current=next;setLanguage(next);stopVoice();translationController.current?.abort();if(!selected)return;const abort=new AbortController();translationController.current=abort;const timer=setTimeout(()=>abort.abort(),55000);const id=selected.id;try{const data=await send({rows:selected.rows},next,abort.signal);if(languageRef.current!==next||abort.signal.aborted)return;setHistory(h=>h.map(r=>r.id===id?{...r,...data,language:next}:r));if(data.noticeCode)setNotice('translationFallback');}catch{if(!abort.signal.aborted&&languageRef.current===next)setNotice('translationFallback');}finally{clearTimeout(timer);}}
 function speak(){if(!report)return;if(speaking){stopVoice();return;}if(!window.speechSynthesis){setNotice('VOICE');return;}const voice=speechSynthesis.getVoices().find(v=>v.lang.split('-')[0]===locale.split('-')[0]);if(!voice){setNotice('VOICE');return;}const utterance=new SpeechSynthesisUtterance([report.summary,...report.rows.map(r=>r.displayName+'. '+r.explanation)].join(' '));utterance.lang=locale;utterance.voice=voice;utterance.rate=.9;utterance.onend=()=>setSpeaking(false);utterance.onerror=()=>{setSpeaking(false);setNotice('VOICE');};setSpeaking(true);speechSynthesis.speak(utterance);}
 const navs:[View,MessageKey,string][]=[['dashboard','dashboard','grid'],['upload','upload','upload'],['history','history','history'],['questions','questions','chat'],['settings','settings','settings']];
 const badge=(r:ExplainedRow)=><span className={'badge '+r.flag}>{symbols[r.flag]} {t(r.flag)}</span>;
 const normal=report?.rows.filter(r=>r.flag==='normal').length||0;const outside=report?.rows.filter(r=>r.flag==='high'||r.flag==='low').length||0;const unknown=report?.rows.filter(r=>r.flag==='not_assessed').length||0;
 const visibleRows=report?.rows.map((r,i)=>({r,i})).filter(({r})=>(filter==='all'||filter==='outside'&&(r.flag==='high'||r.flag==='low')||r.flag===filter)&&(r.displayName+' '+r.nameAsPrinted).toLowerCase().includes(search.toLowerCase()))||[];
 const questions=report?[...report.rows.filter(r=>r.doctorQuestion).map(r=>({category:t('understand'),text:r.displayName+': '+r.doctorQuestion})),{category:t('followUp'),text:t('questionRepeat')},{category:t('monitoring'),text:t('questionMonitor')},{category:t('nextSteps'),text:t('questionInfo')}]:[];
 const historyItems=history.filter(r=>reportName(r).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||r.rows.some(x=>x.flag==='high'||x.flag==='low'))).sort((a,b)=>sort==='name'?reportName(a).localeCompare(reportName(b),locale):sort==='old'?a.date.localeCompare(b.date):b.date.localeCompare(a.date));
 const detail=detailIndex!==null?report?.rows[detailIndex]:null;
 const langSelect=(label:MessageKey)=><label className="lang"><span className="sr">{t(label)}</span><select aria-label={t(label)} value={language} disabled={!!stage} onChange={e=>changeLanguage(e.target.value as Language)}>{LANGUAGES.map((l,i)=><option value={l} key={l} lang={LOCALES[i]}>{NATIVE_NAMES[i]}</option>)}</select></label>;
 const heading=(title:MessageKey,text?:MessageKey)=><div className="page-heading"><div className="eyebrow">{t('companion')}</div><h1>{t(title)}</h1>{text&&<p>{t(text)}</p>}</div>;
 const empty=()=> <section className="empty panel"><Icon name="file"/><h2>{t('empty')}</h2><button className="primary" onClick={()=>go('upload')}>{t('upload')}</button></section>;
 const relation=(r:ExplainedRow)=>t(r.flag==='normal'?'statusNormal':r.flag==='high'?'statusHigh':r.flag==='low'?'statusLow':'statusUnknown');
 return <div className={`${large?'large ':''}${contrast?'contrast':''}`}>
 <a className="skip" href="#main">{t('skip')}</a>
 <aside className="sidebar"><button className="brand" onClick={()=>go('home')} disabled={!!stage} aria-label={t('home')}><span className="brandmark">+</span><span>MEDI<span className="brandlight">EXPLAIN</span></span></button><div className="navlabel">{t('companion')}</div><nav>{navs.map(([v,key,icon])=><button key={v} className={view===v?'navitem active':'navitem'} onClick={()=>go(v)} disabled={!!stage} aria-current={view===v?'page':undefined}><Icon name={icon}/>{t(key)}</button>)}</nav><div className="sidebar-bottom"><div className="privacy-mini"><Icon name="shield"/><strong>{t('understand')}</strong><p>{t('prepareText')}</p></div></div></aside>
 <div className="shell"><header className="topbar"><span className="breadcrumb">{t('companion')}</span><div className="topactions">{langSelect('language')}<button className="primary small" disabled={!!stage} onClick={()=>{removeUpload();setManual('');go('upload');}}>+ {t('newReport')}</button></div></header>
 <main id="main" tabIndex={-1}><div className="page-navigation"><button className="secondary small" disabled={!!stage||navState.cursor===0} onClick={()=>move(-1)}>← {t('back')}</button><button className="secondary small" disabled={!!stage||navState.cursor>=navState.length-1} onClick={()=>move(1)}>{t('forward')} →</button></div>
 {notice&&<div className="notice" role="status">{t(notice)}<button onClick={()=>setNotice(null)} aria-label={t('close')}>×</button></div>}
 {error&&<div className="error" role="alert">{t(error)}</div>}
 {stage?<section className="processing panel" role="status" aria-live="polite"><div className="pulse"><Icon name="file"/></div><h1>{t(stage==='reading'?'processing':'explaining')}</h1><div className="progress"><span/></div><p>{t('wait')}</p><button className="secondary" onClick={cancel}>{t('cancel')}</button></section>:<>
 {view==='home'&&<><section className="hero"><div><div className="eyebrow">{t('companion')}</div><h1>{t('hero')}</h1><p className="hero-copy">{t('heroText')}</p><button className="primary" onClick={()=>go('upload')}>{t('start')} <Icon name="arrow"/></button></div><div className="report-visual"><Icon name="file"/><h2>{t('uploadTitle')}</h2><p>{t('uploadText')}</p><div className="workflow-steps">{(['upload','review','understand'] as MessageKey[]).map((key,i)=><div key={key}><span>{i+1}</span><h3>{t(key)}</h3></div>)}</div><p>{t('verifyText')}</p></div></section><div className="benefits">{(['understand','identify','prepare'] as const).map((key,i)=><div key={key}><span>0{i+1}</span><h3>{t(key)}</h3><p>{t((key+'Text') as MessageKey)}</p></div>)}</div><div className="bottom-note"><Icon name="shield"/>{t('disclaimer')}</div></>}
 {view==='upload'&&<>{heading(rows?'verifyTitle':'uploadTitle',rows?'verifyText':'uploadText')}<div className="upload-grid"><section className="panel">
 {!rows&&<><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0]);}}><div className="upload-icon"><Icon name="upload"/></div><h2>{preparing?t('loading'):upload?.source==='camera'?t('scannedReport'):upload?.file.name||t('drop')}</h2><input ref={chooser} className="sr" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" onChange={e=>{choose(e.target.files?.[0]);e.target.value='';}}/><input ref={cameraPicker} className="sr" type="file" accept="image/*" capture="environment" onChange={e=>{choose(e.target.files?.[0],'camera');e.target.value='';}}/><div className="actions"><button className="primary" disabled={preparing} onClick={()=>chooser.current?.click()}>{t('choose')}</button><button className="secondary" disabled={cameraStarting||preparing} onClick={openCamera}><Icon name="camera"/>{t('scan')}</button></div><small>{t('formats')}</small></div>
 {cameraOpen&&<section className="camera-panel" aria-label={t('scan')}><video ref={video} autoPlay playsInline muted onCanPlay={()=>setCameraReady(true)} aria-label={t('preview')}/><p>{t('cameraGuide')}</p><div className="actions"><button className="primary" disabled={!cameraReady} onClick={capture}>{t('capture')}</button><button className="secondary" onClick={closeCamera}>{t('closeCamera')}</button></div></section>}
 {upload?.url&&<div className="file-preview">{upload.file.type.startsWith('image/')?<img src={upload.url} alt={t('preview')}/>:<object data={upload.url} type="application/pdf" aria-label={t('preview')}><a href={upload.url} target="_blank" rel="noreferrer">{t('openPreview')}</a></object>}<div className="file-meta"><span>{upload.file.type} · {(upload.file.size/1024).toLocaleString(locale,{maximumFractionDigits:0})} KB</span><button className="text-button" onClick={removeUpload}>{t('remove')}</button></div><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{t('consent')}</label><button className="primary full" disabled={!consent||preparing} onClick={readReport}>{t('analyze')} <Icon name="arrow"/></button></div>}
 {ai===false&&<p className="muted">{t('MISSING_KEY')}</p>}
 <div className="manual"><h3>{t('manual')}</h3><p>{t('manualHelp')}</p><label className="sr" htmlFor="manual">{t('manual')}</label><textarea id="manual" value={manual} onChange={e=>setManual(e.target.value)} placeholder={`${t('parameter')} | ${t('value')} | ${t('unit')} | ${t('range')}`} rows={5}/><button className="secondary" disabled={!manual.trim()||preparing} onClick={()=>{setRows(parseText(manual));setUnreadableCount(0);setError(null);closeCamera();}}>{t('review')}</button></div></>}
 {rows&&<>{unreadableCount>0&&<div className="notice">{t('unreadable')} ({unreadableCount.toLocaleString(locale)})</div>}{upload?.url&&<details className="review-preview"><summary>{t('preview')}</summary>{upload.file.type.startsWith('image/')?<img src={upload.url} alt={t('preview')}/>:<object data={upload.url} type="application/pdf" aria-label={t('preview')}><a href={upload.url} target="_blank" rel="noreferrer">{t('openPreview')}</a></object>}</details>}<div className="edit-rows">{rows.map((r,i)=><div className="edit-row" key={i}>{(['nameAsPrinted','value','unit','printedRange'] as const).map(k=><label key={k}>{t(({nameAsPrinted:'parameter',value:'value',unit:'unit',printedRange:'range'} as const)[k])}<input value={r[k]??''} type={k==='value'?'number':'text'} step="any" onChange={e=>setRows(prev=>prev!.map((x,j)=>j===i?{...x,[k]:k==='value'?(e.target.value===''?null:Number(e.target.value)):k==='nameAsPrinted'?e.target.value:e.target.value||null}:x))}/></label>)}<button className="text-button" aria-label={`${t('remove')} ${r.nameAsPrinted}`} onClick={()=>setRows(rows.filter((_,j)=>j!==i))}>×</button></div>)}</div><button className="text-button" disabled={rows.length>=100} onClick={()=>setRows([...rows,{nameAsPrinted:'',value:null,unit:null,printedRange:null}])}>+ {t('addRow')}</button><div className="actions"><button className="primary" disabled={!rows.length||rows.some(r=>!r.nameAsPrinted.trim())} onClick={confirm}>{t('confirm')} <Icon name="arrow"/></button><button className="secondary" onClick={()=>setRows(null)}>{t('back')}</button></div></>}
 </section><aside className="upload-help"><section className="panel"><Icon name="shield"/><h2>{t('privacy')}</h2><p>{t('privacyText')}</p></section><div className="help"><Icon name="camera"/><h3>{t('scan')}</h3><p>{t('photoTip')}</p></div></aside></div></>}
 {view==='dashboard'&&(!report?empty():<>{heading('report')}<p className="report-meta">{reportName(report)} · {new Date(report.date).toLocaleDateString(locale,{day:'numeric',month:'long',year:'numeric'})} · {report.rows.length.toLocaleString(locale)} {t('results')}</p><div className="report-tools"><button className="secondary small" onClick={speak}><Icon name="audio"/>{t(speaking?'stop':'listen')}</button><button className="secondary small" onClick={()=>window.print()}>{t('print')}</button></div><div className="stats">{([['normal',normal,'normal','✓'],['outside',outside,'high','↑'],['needsVerify',unknown,'not_assessed','?']] as const).map(([key,count,css,symbol])=><button className="stat" key={key} onClick={()=>setFilter(key==='needsVerify'?'not_assessed':key)}><span className={'stat-symbol '+css}>{symbol}</span><div><small>{t(key)}</small><strong>{count.toLocaleString(locale)}<span>{t('results')}</span></strong></div></button>)}</div><section className="summary panel"><div className="summary-icon"><Icon name="file"/></div><div><h2>{t('summary')}</h2><p>{report.summary}</p><p className="muted">{t('rangeNotice')}</p></div></section><div className="section-heading"><h2>{t('understand')}</h2><span>{visibleRows.length.toLocaleString(locale)} {t('results')}</span></div><div className="filters"><div className="filter-buttons">{(['all','outside','normal','not_assessed'] as const).map(key=><button key={key} className={filter===key?'selected':''} onClick={()=>setFilter(key)} aria-pressed={filter===key}>{t(key)}</button>)}</div><input aria-label={t('search')} placeholder={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="results">{visibleRows.map(({r,i})=><button className="result-row" key={i} onClick={()=>setDetailIndex(i)}><div className="result-name"><strong>{r.displayName}</strong><span>{t('range')}: {r.printedRange||t('missingRange')}</span></div><div className="result-value">{r.value?.toLocaleString(locale,{maximumFractionDigits:10})??'—'}<small>{r.unit}</small></div>{badge(r)}<p>{r.explanation}</p><span className="row-arrow">↗</span></button>)}{!visibleRows.length&&<div className="panel">{t('noResults')}</div>}</div><section className="doctor-callout"><div><h2>{t('visit')}</h2><p>{t('prepareText')}</p></div><button className="primary" onClick={()=>go('questions')}>{t('questions')} <Icon name="arrow"/></button></section><div className="bottom-note"><Icon name="shield"/>{t('disclaimer')}</div></>)}
 {view==='questions'&&<>{heading('visit','prepareText')}{!report?empty():<><div className="report-tools"><span>{reportName(report)}</span><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(questions.map(q=>q.text).join('\n\n'));setNotice('copied');}catch{setNotice('copyFailed');}}}>{t('copy')}</button><button className="primary" onClick={()=>window.print()}>{t('print')}</button></div><div className="questions">{questions.map((q,i)=><div className="question panel" key={i}><span className="question-number">{(i+1).toLocaleString(locale)}</span><div><span className="tiny-title">{q.category}</span><h3>{q.text}</h3></div></div>)}</div><div className="notice">{t('visitText')}</div></>}</>}
 {view==='history'&&<>{heading('history',saveLocal?'historySaved':'historySession')}<div className="filters"><input aria-label={t('search')} placeholder={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label={t('results')} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t('all')}</option><option value="outside">{t('outside')}</option></select><select aria-label={t('nameSort')} value={sort} onChange={e=>setSort(e.target.value)}><option value="new">{t('newest')}</option><option value="old">{t('oldest')}</option><option value="name">{t('nameSort')}</option></select></div>{!history.length?empty():<div className="history-list">{historyItems.map(r=><button className="history-row panel" key={r.id} onClick={()=>go('dashboard',r.id)}><div className="document-icon"><Icon name="file"/></div><div><h3>{reportName(r)}</h3><p>{new Date(r.date).toLocaleDateString(locale)} · {r.rows.length.toLocaleString(locale)} {t('results')}</p></div><span className="badge high">{r.rows.filter(x=>x.flag==='high'||x.flag==='low').length.toLocaleString(locale)} {t('outside')}</span><Icon name="arrow"/></button>)}{!historyItems.length&&<p>{t('noResults')}</p>}</div>}</>}
 {view==='settings'&&<>{heading('settings','preferences')}<section className="panel settings"><div className="setting"><h3>{t('language')}</h3>{langSelect('language')}</div><div className="setting"><h3>{t('largeText')}</h3><input type="checkbox" aria-label={t('largeText')} checked={large} onChange={e=>setLarge(e.target.checked)}/></div><div className="setting"><h3>{t('contrast')}</h3><input type="checkbox" aria-label={t('contrast')} checked={contrast} onChange={e=>setContrast(e.target.checked)}/></div><div className="setting"><div><h3>{t('saveLocal')}</h3><p>{t('saveLocalText')}</p></div><input type="checkbox" aria-label={t('saveLocal')} checked={saveLocal} onChange={e=>setSaveLocal(e.target.checked)}/></div><div className="setting"><h3>{t('clear')}</h3><button className="danger" onClick={()=>{if(!window.confirm(t('clearConfirm')))return;try{localStorage.removeItem('mediexplain-history');localStorage.removeItem('mediexplain-settings');}catch{setNotice('STORAGE');return;}translationController.current?.abort();setHistory([]);setActiveId(null);setLarge(false);setContrast(false);setSaveLocal(false);removeUpload();setManual('');setNotice('cleared');locations.current=[{view:'settings'}];cursor.current=0;setNavState({cursor:0,length:1});}}>{t('clear')}</button></div></section><section className="panel legal"><h2>{t('privacy')}</h2><p>{t('privacyText')}</p><p>{t('saveLocalText')}</p><p>{t('disclaimer')}</p></section></>}
 </>}
 </main><footer>MEDIEXPLAIN <span>{t('companion')}</span><button className="text-button" disabled={!!stage} onClick={()=>go('settings')}>{t('privacy')}</button></footer></div>
 <dialog ref={dialog} onCancel={()=>setDetailIndex(null)} onClick={e=>{if(e.target===e.currentTarget)setDetailIndex(null);}} aria-labelledby="detail-title">{detail&&<><button className="close" onClick={()=>setDetailIndex(null)} aria-label={t('close')}>×</button><div className="eyebrow">{t('understand')}</div><h2 id="detail-title">{detail.displayName}</h2>{badge(detail)}<div className="detail-value">{detail.value?.toLocaleString(locale,{maximumFractionDigits:10})??'—'} <span>{detail.unit}</span></div><p>{t('range')}: <strong>{detail.printedRange||t('missingRange')}</strong></p><p className="muted">{t('original')}: <span lang="und">{detail.nameAsPrinted}</span></p><h3>{t('what')}</h3><p>{detail.measures}</p><h3>{t('means')}</h3><p>{relation(detail)}</p><p>{detail.explanation}</p>{detail.reason&&<div className="notice">{detail.reason}</div>}<h3>{t('factors')}</h3><p>{t('factorsText')}</p><h3>{t('questions')}</h3><p>{detail.doctorQuestion||t('questionMeaning')}</p><p className="muted">{t('visitText')}</p></>}</dialog>
 </div>;
}
